//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _LayoutResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _LayoutResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("www.Views.Shared._LayoutResources", typeof(_LayoutResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string fb_icon {
            get {
                return ResourceManager.GetString("fb_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **No Purchase Necessary. Subject to the Official Rules at &lt;a href=&quot;http://www.facebook.com/cityofmoncton&quot; target=&quot;_blank&quot;&gt;www.facebook.com/cityofmoncton&lt;/a&gt;. Open to legal residents of Canada who have reached the age of majority in his/her province or territory. Submission Period ends at 11:59:59 PM (ET) on August 26, 2013: Voting Period starts at 9:00:00 AM (ET) on September 3, 2013 and ends at 11:59:59 PM (ET) on October 22, 2013. Fourteen Submission Prizes ranging from $40.00 to $220.00 CDN. Four Judges  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string footer_legal {
            get {
                return ResourceManager.GetString("footer_legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string NavRules {
            get {
                return ResourceManager.GetString("NavRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string redirect_url {
            get {
                return ResourceManager.GetString("redirect_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I just submitted my   Moncton Moment! I now have a chance to win one of 21 amazing weekly prizes,   one of 4 Judges’ awards as well as, the grand or runner-up prizes. To enter   your own Moncton Moment check out the contest!.
        /// </summary>
        public static string ShareDescription {
            get {
                return ResourceManager.GetString("ShareDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moncton Moments VIDEO and PHOTO Contest!.
        /// </summary>
        public static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moncton Moments.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
    }
}
