//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _RegistrationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _RegistrationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("www.Views.Register._RegistrationResource", typeof(_RegistrationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn-e.
        /// </summary>
        public static string Index_ButtonSubmit {
            get {
                return ResourceManager.GetString("Index_ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Index_ButtonSubmitAlt {
            get {
                return ResourceManager.GetString("Index_ButtonSubmitAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn-e.
        /// </summary>
        public static string Index_ClassSubmit {
            get {
                return ResourceManager.GetString("Index_ClassSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm you are the age of majority in your province or territory of residence by declaring your year of birth..
        /// </summary>
        public static string Index_HintYearOfBirth {
            get {
                return ResourceManager.GetString("Index_HintYearOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agreed to abide by the &lt;a href=&quot;/facebook/monctonMomentsSubmission/Home/RulesPopUp&quot; class=&quot;rulesPopUp&quot;&gt;Official Rules&lt;/a&gt;..
        /// </summary>
        public static string Index_LabelAcceptRules {
            get {
                return ResourceManager.GetString("Index_LabelAcceptRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Address.
        /// </summary>
        public static string Index_LabelAddress1 {
            get {
                return ResourceManager.GetString("Index_LabelAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Index_LabelAddress2 {
            get {
                return ResourceManager.GetString("Index_LabelAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Index_LabelCity {
            get {
                return ResourceManager.GetString("Index_LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth:.
        /// </summary>
        public static string Index_LabelDateOfBirth {
            get {
                return ResourceManager.GetString("Index_LabelDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Index_LabelEmail {
            get {
                return ResourceManager.GetString("Index_LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Index_LabelFirstName {
            get {
                return ResourceManager.GetString("Index_LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Index_LabelLastName {
            get {
                return ResourceManager.GetString("Index_LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr..
        /// </summary>
        public static string Index_LabelMr {
            get {
                return ResourceManager.GetString("Index_LabelMr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms..
        /// </summary>
        public static string Index_LabelMs {
            get {
                return ResourceManager.GetString("Index_LabelMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Index_LabelPostalCode {
            get {
                return ResourceManager.GetString("Index_LabelPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province:.
        /// </summary>
        public static string Index_LabelProvince {
            get {
                return ResourceManager.GetString("Index_LabelProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Index_LabelProvince1 {
            get {
                return ResourceManager.GetString("Index_LabelProvince1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agreed to abide by the &lt;a href=&quot;/facebook/monctonMomentsSubmission/Home/RulesPopUp&quot; class=&quot;rulesPopUp&quot;&gt;Official Rules&lt;/a&gt;..
        /// </summary>
        public static string Index_LabelRules {
            get {
                return ResourceManager.GetString("Index_LabelRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salutation.
        /// </summary>
        public static string Index_LabelSalutation {
            get {
                return ResourceManager.GetString("Index_LabelSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Index_LabelTelephone {
            get {
                return ResourceManager.GetString("Index_LabelTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of birth.
        /// </summary>
        public static string Index_LabelYearOfBirth {
            get {
                return ResourceManager.GetString("Index_LabelYearOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your First Name:.
        /// </summary>
        public static string Index_LabelYourFirstName {
            get {
                return ResourceManager.GetString("Index_LabelYourFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To VOTE, please enter your information:.
        /// </summary>
        public static string Index_PageSubTitle {
            get {
                return ResourceManager.GetString("Index_PageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Age of majority.
        /// </summary>
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string Index_Select {
            get {
                return ResourceManager.GetString("Index_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out all the fields below. Don’t worry, you’ll only have to do this once. It’s so &lt;br /&gt;we remember you when you come back and we’ll be able to get ahold of you if you win!.
        /// </summary>
        public static string Registration_Intro {
            get {
                return ResourceManager.GetString("Registration_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About you!.
        /// </summary>
        public static string Registration_PageTitle {
            get {
                return ResourceManager.GetString("Registration_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Denotes Required Field.
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Address field is required..
        /// </summary>
        public static string ValidationAddress {
            get {
                return ResourceManager.GetString("ValidationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the Official Rules..
        /// </summary>
        public static string ValidationAgreeRules {
            get {
                return ResourceManager.GetString("ValidationAgreeRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The City field is required..
        /// </summary>
        public static string ValidationCity {
            get {
                return ResourceManager.GetString("ValidationCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Date of Birth is required..
        /// </summary>
        public static string ValidationDateOfBirth {
            get {
                return ResourceManager.GetString("ValidationDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Day of Birth field is required..
        /// </summary>
        public static string ValidationDayOfBirth {
            get {
                return ResourceManager.GetString("ValidationDayOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email address..
        /// </summary>
        public static string ValidationEmail {
            get {
                return ResourceManager.GetString("ValidationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ValidationField {
            get {
                return ResourceManager.GetString("ValidationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The First Name field is required..
        /// </summary>
        public static string ValidationFirstName {
            get {
                return ResourceManager.GetString("ValidationFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Last Name field is required..
        /// </summary>
        public static string ValidationLastName {
            get {
                return ResourceManager.GetString("ValidationLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Month of Birth field is required..
        /// </summary>
        public static string ValidationMonthOfBirth {
            get {
                return ResourceManager.GetString("ValidationMonthOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Postal Code field is required..
        /// </summary>
        public static string ValidationPostalCode {
            get {
                return ResourceManager.GetString("ValidationPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Province field is required..
        /// </summary>
        public static string ValidationProvince {
            get {
                return ResourceManager.GetString("ValidationProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Salutation field is required..
        /// </summary>
        public static string ValidationSalutation {
            get {
                return ResourceManager.GetString("ValidationSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Telephone field is required..
        /// </summary>
        public static string ValidationTelephone {
            get {
                return ResourceManager.GetString("ValidationTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Year of Birth field is required..
        /// </summary>
        public static string ValidationYearOfBirth {
            get {
                return ResourceManager.GetString("ValidationYearOfBirth", resourceCulture);
            }
        }
    }
}
