//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _HomeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _HomeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("www.Views.Home._HomeResources", typeof(_HomeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /facebook/monctonMomentsSubmission/Content/images/btn-start.png.
        /// </summary>
        public static string Home_Btn {
            get {
                return ResourceManager.GetString("Home_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;What do you love about Moncton?&lt;br /&gt;Share your favourite Moncton&lt;br /&gt;Moment and you could win*!&lt;/h1&gt;
        ///
        ///        &lt;h2&gt;21 AWESOME WEEKLY PRIZES&lt;/h2&gt;
        ///
        ///        &lt;p class=&quot;bluel&quot;&gt;&lt;span class=&quot;lrg&quot;&gt;Grand prize package&lt;/span&gt; &lt;br&gt;and runner-up prizes for the top two &lt;br&gt;VIDEO and PHOTO vote getters!&lt;/p&gt;
        ///
        ///        &lt;h3&gt;4 Judges’ Awards&lt;/h3&gt;
        ///
        ///        &lt;p class=&quot;bluel&quot;&gt;Over $5,000 in total prize value to be won!&lt;/p&gt;
        ///
        ///        &lt;p class=&quot;sml&quot;&gt;Submit your favourite PHOTO or VIDEO of you or&lt;br /&gt;someone you know  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Home_Copy {
            get {
                return ResourceManager.GetString("Home_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn-e.
        /// </summary>
        public static string Index_btn_enter {
            get {
                return ResourceManager.GetString("Index_btn_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Now!.
        /// </summary>
        public static string Index_ButtonPlayNow {
            get {
                return ResourceManager.GetString("Index_ButtonPlayNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the MAJESTA Soft &amp; Green Giveaway for your chance to WIN* 1 of 20 MAJESTA Prize Packs! You can enter daily, until April 19&lt;sup&gt;th&lt;/sup&gt;!.
        /// </summary>
        public static string Index_Intro1 {
            get {
                return ResourceManager.GetString("Index_Intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enter the giveaway, enter your email below..
        /// </summary>
        public static string Index_Intro2 {
            get {
                return ResourceManager.GetString("Index_Intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read the &lt;a href=&quot;/facebook/greenAndSoftGiveAway/Home/RulesPopUp&quot; class=&quot;rulesPopUp&quot;&gt;Official Rules&lt;/a&gt; and the &lt;a href=&quot;/facebook/greenAndSoftGiveAway/Home/PrivacyPopUp&quot; class=&quot;privacyPopUp&quot;&gt;Privacy Policy&lt;/a&gt; and agree to be bound and abide by them..
        /// </summary>
        public static string Index_LabelAcceptRules {
            get {
                return ResourceManager.GetString("Index_LabelAcceptRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address:.
        /// </summary>
        public static string Index_LabelEmail {
            get {
                return ResourceManager.GetString("Index_LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt-like.png.
        /// </summary>
        public static string Like_Title {
            get {
                return ResourceManager.GetString("Like_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‘Like’ this page for your chance to Win 1 of 20 MAJESTA Prize Packs!.
        /// </summary>
        public static string Like_Title_Alt {
            get {
                return ResourceManager.GetString("Like_Title_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft &amp; Green Giveaways.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserAgreementBody {
            get {
                return ResourceManager.GetString("UserAgreementBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the Official Rules..
        /// </summary>
        public static string ValidationAgreeRules {
            get {
                return ResourceManager.GetString("ValidationAgreeRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email address..
        /// </summary>
        public static string ValidationEmail {
            get {
                return ResourceManager.GetString("ValidationEmail", resourceCulture);
            }
        }
    }
}
