//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("www.Views.Message._MessageResources", typeof(_MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred in your registration process. &lt;br&gt;&lt;br&gt;Please try again.
        ///If the problem persists please contact  &lt;a href=&quot;mailto:majesta@modernmedia.ca&quot;&gt;majesta@modernmedia.ca&lt;/a&gt;..
        /// </summary>
        public static string AccountCreationFailed_Message {
            get {
                return ResourceManager.GetString("AccountCreationFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string AccountCreationFailed_PageTitle {
            get {
                return ResourceManager.GetString("AccountCreationFailed_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred when you tried to update you profile. &lt;br&gt;&lt;br&gt;Please try again.
        ///If the problem persists please contact &lt;a href=&quot;mailto:majesta@modernmedia.ca&quot;&gt;majesta@modernmedia.ca&lt;/a&gt;..
        /// </summary>
        public static string AccountUpdateFailed_Message {
            get {
                return ResourceManager.GetString("AccountUpdateFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string AccountUpdateFailed_PageTitle {
            get {
                return ResourceManager.GetString("AccountUpdateFailed_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has already been submitted today. &lt;br&gt;&lt;br&gt;Please come back tomorrow. 
        ///A contest day is defined as 12:00:00 a.m. to &lt;br&gt;11:59:59 p.m. Eastern Time (ET)..
        /// </summary>
        public static string AlreadyEntered_Message {
            get {
                return ResourceManager.GetString("AlreadyEntered_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string AlreadyEntered_PageTitle {
            get {
                return ResourceManager.GetString("AlreadyEntered_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry but an error has occurred when entering your ballot.  &lt;br&gt;&lt;br&gt;Please try again. 
        ///If the error persists please contact: &lt;a href=&quot;mailto:majesta@modernmedia.ca&quot;&gt;majesta@modernmedia.ca&lt;/a&gt;..
        /// </summary>
        public static string BallotError_Message {
            get {
                return ResourceManager.GetString("BallotError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string BallotError_PageTitle {
            get {
                return ResourceManager.GetString("BallotError_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to †No Purchase Necessary. Subject to the Official Rules at &lt;a href=&quot;http://www.majesta.com&quot; target=&quot;_blank&quot;&gt;www.majesta.com&lt;/a&gt;. Open to residents of Canada who are of the age of majority in his/her province or territory of residence. Play the Tree Twists game and be entered for a chance to win $10,000 CDN. Contest closes 11:59 PM (ET) on April 26, 2013. One Prize is available to be won and consists of $10,000 CDN. Random draw: May 9, 2013. Odds of winning depend on the total number of eligible entries receiv [rest of string was truncated]&quot;;.
        /// </summary>
        public static string contest_legal {
            get {
                return ResourceManager.GetString("contest_legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.majestatreesofknowledge.ca.
        /// </summary>
        public static string contest_legal_url {
            get {
                return ResourceManager.GetString("contest_legal_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moncton Moments ended at 11:59PM EST, October 22nd, 2013. &lt;br&gt;&lt;br&gt;Thanks for your participation!.
        /// </summary>
        public static string ContestClosed_Message {
            get {
                return ResourceManager.GetString("ContestClosed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string ContestClosed_PageTitle {
            get {
                return ResourceManager.GetString("ContestClosed_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest opens May 21st, 2013, at 9:00AM EST..
        /// </summary>
        public static string ContestNotOpen_Message {
            get {
                return ResourceManager.GetString("ContestNotOpen_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string ContestNotOpen_PageTitle {
            get {
                return ResourceManager.GetString("ContestNotOpen_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must authenticate this Facebook Application in order to enter this contest..
        /// </summary>
        public static string FacebookAuthenticationFailed_Message {
            get {
                return ResourceManager.GetString("FacebookAuthenticationFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string FacebookAuthenticationFailed_PageTitle {
            get {
                return ResourceManager.GetString("FacebookAuthenticationFailed_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred from your request. Please try again. &lt;br&gt;&lt;br&gt;If the error persists please contact 
        ///&lt;a href=&quot;mailto:majesta@modernmedia.ca&quot;&gt;majesta@modernmedia.ca&lt;/a&gt;..
        /// </summary>
        public static string Index_Message {
            get {
                return ResourceManager.GetString("Index_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string Index_PageTitle {
            get {
                return ResourceManager.GetString("Index_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files that you have submitted..
        /// </summary>
        public static string MyFiles {
            get {
                return ResourceManager.GetString("MyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be the age of majority in your province or territory of residence to participate in the MAJESTA Soft &amp; Green Giveaways..
        /// </summary>
        public static string NotAgeOfMajority_Message {
            get {
                return ResourceManager.GetString("NotAgeOfMajority_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string NotAgeOfMajority_PageTitle {
            get {
                return ResourceManager.GetString("NotAgeOfMajority_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need your parent&apos;s permission. FPO..
        /// </summary>
        public static string ParentalPermission_Message {
            get {
                return ResourceManager.GetString("ParentalPermission_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string ParentalPermission_PageTitle {
            get {
                return ResourceManager.GetString("ParentalPermission_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired due to inactivity. &lt;br&gt;&lt;br&gt;Go to the main Entry page to start the entry process again.   &lt;br&gt;&lt;br&gt;Your session will expire after twenty (20) minutes of inactivity on the site..
        /// </summary>
        public static string SessionLost_Message {
            get {
                return ResourceManager.GetString("SessionLost_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string SessionLost_PageTitle {
            get {
                return ResourceManager.GetString("SessionLost_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thanks.png.
        /// </summary>
        public static string thanks_img_title {
            get {
                return ResourceManager.GetString("thanks_img_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! Your Moncton Moment was successfully uploaded..
        /// </summary>
        public static string thanks_img_title_alt {
            get {
                return ResourceManager.GetString("thanks_img_title_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;It may take a day or so to see your Video or Photo on the Facebook page.&lt;/p&gt;
        ///
        ///&lt;p&gt;But don’t stop shooting; you can submit a new Video or Photo EVERYDAY up &lt;strong&gt;until August 26&lt;sup&gt;th&lt;/sup&gt;!&lt;/strong&gt; &lt;/p&gt;
        ///
        ///&lt;p&gt;And remember, &lt;strong&gt;voting for grand prizes opens September 3&lt;sup&gt;rd&lt;/sup&gt;&lt;/strong&gt;, so remind your friends to check out your submissions and vote for you then. &lt;/p&gt;
        ///
        ///&lt;p&gt;&lt;strong&gt;Let’s show the world how great Moncton truly is!&lt;/strong&gt;&lt;/p&gt;.
        /// </summary>
        public static string thanks_text {
            get {
                return ResourceManager.GetString("thanks_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Upload.
        /// </summary>
        public static string UploadFailed_Message {
            get {
                return ResourceManager.GetString("UploadFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we were unable to upload your file. Please try again or contact us at &lt;a href=&quot;mailto:majesta@modernmedia.ca&quot;&gt;majesta@modernmedia.ca&lt;/a&gt;..
        /// </summary>
        public static string UploadFailed_PageTitle {
            get {
                return ResourceManager.GetString("UploadFailed_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address you entered does not exist in the online community. &lt;br&gt;&lt;br&gt;Please enter another email address.  If the problem persists please contact  &lt;a href=&quot;mailto:majesta@modernmedia.ca&quot;&gt;majesta@modernmedia.ca&lt;/a&gt;..
        /// </summary>
        public static string UserDoesNotExist_Message {
            get {
                return ResourceManager.GetString("UserDoesNotExist_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string UserDoesNotExist_PageTitle {
            get {
                return ResourceManager.GetString("UserDoesNotExist_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re Sorry..
        /// </summary>
        public static string WeAreSorry {
            get {
                return ResourceManager.GetString("WeAreSorry", resourceCulture);
            }
        }
    }
}
