//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _UploadResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _UploadResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("www.Views.Upload._UploadResource", typeof(_UploadResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btn-upload-e.
        /// </summary>
        public static string ButtonUpload {
            get {
                return ResourceManager.GetString("ButtonUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload now!.
        /// </summary>
        public static string ButtonUploadAlt {
            get {
                return ResourceManager.GetString("ButtonUploadAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filebutton.
        /// </summary>
        public static string filebutton {
            get {
                return ResourceManager.GetString("filebutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Photo formats:&lt;br /&gt;
        ///*Video Formats: wmv, 3gp, avi, mov, mp4, mpeg/mpegs, flv ,swf, mkv or webm.
        /// </summary>
        public static string Help_Formats {
            get {
                return ResourceManager.GetString("Help_Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Step 1:&lt;/strong&gt; &lt;br /&gt;Capture your video* &lt;br /&gt;(45-90 sec. MAX) or photo..
        /// </summary>
        public static string Help_Step1 {
            get {
                return ResourceManager.GetString("Help_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Step 2:&lt;/strong&gt; &lt;br /&gt;Upload your video or &lt;br /&gt;photo to your computer..
        /// </summary>
        public static string Help_Step2 {
            get {
                return ResourceManager.GetString("Help_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Step 3:&lt;/strong&gt; &lt;br /&gt;Submit your video or photo &lt;br /&gt;on this Moncton Moments Facebook app..
        /// </summary>
        public static string Help_Step3 {
            get {
                return ResourceManager.GetString("Help_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to upload.
        /// </summary>
        public static string Help_Title {
            get {
                return ResourceManager.GetString("Help_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you submit here are a few important things to remember:.
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of Video or Photo Caption.
        /// </summary>
        public static string LabelCaption {
            get {
                return ResourceManager.GetString("LabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location In Moncton.
        /// </summary>
        public static string LabelCityIn {
            get {
                return ResourceManager.GetString("LabelCityIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Outside Moncton Area (see Official Rules for details).
        /// </summary>
        public static string LabelCityOut {
            get {
                return ResourceManager.GetString("LabelCityOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I confirm that I have permission to publish from all individual(s) 19 years of age or older who are appearing in my Video or Photo..
        /// </summary>
        public static string LabelConcent19 {
            get {
                return ResourceManager.GetString("LabelConcent19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I confirm that I am the parent or legal guardian of all individual(s) 18 years of age or younger who are appearing in my Video or Photo..
        /// </summary>
        public static string LabelConcentGuardian {
            get {
                return ResourceManager.GetString("LabelConcentGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your Video or Photo was taken &lt;strong&gt;outside the Moncton area&lt;/strong&gt;, complete the following sentence in 50 words or less (English or French), “My Moncton Moment is…”.
        /// </summary>
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click “Browse” to select your file.
        /// </summary>
        public static string LabelFile {
            get {
                return ResourceManager.GetString("LabelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your Video or Photo was taken &lt;strong&gt;in the Moncton area&lt;/strong&gt; please tell us where it was taken, i.e. Main St..
        /// </summary>
        public static string LabelLocation {
            get {
                return ResourceManager.GetString("LabelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to upload your favourite Moncton Moment VIDEO or PHOTO?.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Denotes Required Field.
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the &lt;a href=&quot;/facebook/monctonMomentsSubmission/Home/RulesPopUp&quot; class=&quot;rulesPopUp&quot;&gt;Official Rules&lt;/a&gt; – (Section 4 is particularly interesting, it’s all about submission rules and requirements)..
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your video or photo is the correct format and does not exceed 250MB..
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your submitted Video or Photo will be posted on Facebook for the public to view. Check out the &lt;a href=&quot;/facebook/monctonMomentsSubmission/Home/RulesPopUp&quot; class=&quot;rulesPopUp&quot;&gt;Official Rules&lt;/a&gt; on this one if you’re not clear..
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to upload.
        /// </summary>
        public static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of Video or Photo Caption  is required..
        /// </summary>
        public static string ValidationCaption {
            get {
                return ResourceManager.GetString("ValidationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission to publish from all individual(s) is required..
        /// </summary>
        public static string ValidationConcent19 {
            get {
                return ResourceManager.GetString("ValidationConcent19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent or legal guardian concent is required..
        /// </summary>
        public static string ValidationConcentGuardian {
            get {
                return ResourceManager.GetString("ValidationConcentGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file is required..
        /// </summary>
        public static string ValidationFile {
            get {
                return ResourceManager.GetString("ValidationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is required..
        /// </summary>
        public static string ValidationLocation {
            get {
                return ResourceManager.GetString("ValidationLocation", resourceCulture);
            }
        }
    }
}
